In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/tmdb_5000_movies.csv')
credit= pd.read_csv('/content/tmdb_5000_credits.csv')

In [ ]:
credit.isnull().sum()
data=data.merge(credit,on='title')

In [ ]:
#data.info()
low=data[data.budget==0]
print(low)

      budget                                             genres  \
265        0  [{"id": 35, "name": "Comedy"}, {"id": 14, "nam...   
321        0                     [{"id": 35, "name": "Comedy"}]   
359        0  [{"id": 12, "name": "Adventure"}, {"id": 16, "...   
406        0  [{"id": 18, "name": "Drama"}, {"id": 16, "name...   
409        0  [{"id": 18, "name": "Drama"}, {"id": 10402, "n...   
...      ...                                                ...   
4801       0                      [{"id": 18, "name": "Drama"}]   
4803       0  [{"id": 10769, "name": "Foreign"}, {"id": 53, ...   
4806       0  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4807       0                                                 []   
4808       0                [{"id": 99, "name": "Documentary"}]   

                                               homepage      id  \
265                                                 NaN   10588   
321                                                 NaN   779

In [ ]:
#extract year from release date and fill mode value if null
data['year'] = pd.to_datetime(data['release_date'], errors='coerce').dt.year
mode_year =data['year'].mode()[0]
data['year'].fillna(mode_year, inplace=True)
#demographic filtering in this we will filter based on the average review given by the all the reviewer and
#than we will see which has avergae good review that will recoomended to somone because if  a movie reviewed
# good by most of the reviwer than it should be good

<ipython-input-64-2683b77c4f18>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['year'].fillna(mode_year, inplace=True)


In [ ]:
#first we have to calculate a formula to find review score of that movie and we have to use all the movie review so that it will
#be based on combined people not biased
#-- first we need a minimum number of votes required for a movie to get a score bcs if only 5 person have reviewd 5 star than it become very good that is not comletely true
#-- new movies will get hyped so it will get more postive revies and old one will get less as time goes
#--

In [ ]:
#i will take min based on highest no. of review on 30% of movies means movies with higher no. of reviw given to films that has value
#of reviwer bigger than 70% of reviwed movies
min=data['vote_count'].quantile(0.95)
movie_data = data.copy().loc[data['vote_count']>=min]
print(movie_data.shape,data.shape)
C= data['vote_average'].mean()


(241, 24) (4809, 24)


In [ ]:
def movie_sc(data,C=C):
    V = data['vote_count']
    R = data['vote_average']
    Y = data['year']
    B = data['budget']

    return (V*R)/Y

movie_data['score']=movie_data.apply(movie_sc,axis=1)


In [ ]:
#Sort movies based on score calculated above
movie_data = movie_data.sort_values('score', ascending=False)

#Print the top 15 movies
movie_data[['title', 'vote_count', 'vote_average', 'score']].head(10)


title  vote_count  vote_average      score
96                 Inception       13752           8.1  55.418507
65           The Dark Knight       12002           8.2  49.012151
95              Interstellar       10867           8.1  43.705412
16              The Avengers       11776           7.4  43.311332
0                     Avatar       11800           7.2  42.289696
788                 Deadpool       10995           7.4  40.358631
287         Django Unchained       10099           7.8  39.151193
662               Fight Club        9413           8.3  39.083492
94   Guardians of the Galaxy        9742           7.9  38.213406
634               The Matrix        8907           7.9  35.200250

In [ ]:
row_data = data.iloc[662]
print(row_data)

budget                                                           63000000
genres                                      [{"id": 18, "name": "Drama"}]
homepage                       http://www.foxmovies.com/movies/fight-club
id                                                                    550
keywords                [{"id": 825, "name": "support group"}, {"id": ...
original_language                                                      en
original_title                                                 Fight Club
overview                A ticking-time-bomb insomniac and a slippery s...
popularity                                                     146.757391
production_companies    [{"name": "Regency Enterprises", "id": 508}, {...
production_countries    [{"iso_3166_1": "DE", "name": "Germany"}, {"is...
release_date                                                   1999-10-15
revenue                                                         100853753
runtime                               

In [ ]:
movies = pd.read_csv('/content/tmdb_5000_movies.csv')
credit= pd.read_csv('/content/tmdb_5000_credits.csv')


In [ ]:
movies=movies.merge(credit,on='title')

In [ ]:
#change release date int only year
movies.info()
movies['year'] = pd.to_datetime(movies['release_date'], errors='coerce').dt.year
mode_year =movies['year'].mode()[0]
movies['year'].fillna(mode_year, inplace=True)

here we are doing content filtering so we are not gonna need vote and review because we will recoomend based on oersonal choices not by others choices

In [ ]:
movies=movies[['movie_id','cast','crew','title','runtime','year','overview','genres','keywords']]

In [ ]:
movies.isnull().sum()

movie_id    0
cast        0
crew        0
title       0
runtime     2
year        0
overview    3
genres      0
keywords    0
dtype: int64

In [ ]:
movies.dropna(inplace=True)

In [ ]:
movies.isnull().sum()
movies.shape

(4806, 9)

In [ ]:
movies.head(5)

movie_id                                               cast  \
0     19995  [{"cast_id": 242, "character": "Jake Sully", "...   
1       285  [{"cast_id": 4, "character": "Captain Jack Spa...   
2    206647  [{"cast_id": 1, "character": "James Bond", "cr...   
3     49026  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4     49529  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   

                                      title  runtime    year  \
0                                    Avatar    162.0  2009.0   
1  Pirates of the Caribbean: At World's End    169.0  2007.0   
2                                   Spectre    148.0  2015.0   
3                     The Dark Knight Rises    165.0  2012.0   
4                               John Carter    132.0  2012.0   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                              genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id":...  
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4  [{"id": 818, "name": "based on novel"}, {"id":...

In [ ]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
import ast
result=ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')
print(result)
print(result[1]['name'])

[{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]
Adventure


In [ ]:
import ast
#CHANGE GENRES to only name of genres and remove id
#ast.literal_eval change strings into list of dictionary because we need list to loop over to take only name and also to  merege all this column we need it in list form not strings
#it will convert only a single row to apply on all row we have to use applu function
def convert(obj):
  lst=[]
  for item  in ast.literal_eval(obj):
    lst.append(item['name'])
  return lst
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [ ]:
movies['genres'] =   movies['genres'].apply(convert)

In [ ]:
#change movie keyword to only have name that is tag like space travel or romance
movies['keywords']=movies['keywords'].apply(convert)

In [ ]:
movies.iloc[0].cast
# here we will extract only top 3 actor names from a movie
def convert1(obj):
  lst=[]
  a=0
  for i in ast.literal_eval(obj):
    if(a<3):
       lst.append(i['name'])
       a=a+1
    else:
      break
  return lst
movies['cast']=movies['cast'].apply(convert1)

In [ ]:
movies.head()

movie_id                                              cast  \
0     19995  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1       285     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2    206647      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3     49026      [Christian Bale, Michael Caine, Gary Oldman]   
4     49529    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                                                crew  \
0  [{"credit_id": "52fe48009251416c750aca23", "de...   
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...   
2  [{"credit_id": "54805967c3a36829b5002c41", "de...   
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...   
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...   

                                      title  runtime    year  \
0                                    Avatar    162.0  2009.0   
1  Pirates of the Caribbean: At World's End    169.0  2007.0   
2                                   Spectre    148.0  2015.0   
3                     The Dark Knight Rises    165.0  2012.0   
4                               John Carter    132.0  2012.0   

                                            overview  \
0  In the 22nd century, a paraplegic Marine is di...   
1  Captain Barbossa, long believed to be dead, ha...   
2  A cryptic message from Bond’s past sends him o...   
3  Following the death of District Attorney Harve...   
4  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...  
1  [ocean, drug abuse, exotic island, east india ...  
2  [spy, based on novel, secret agent, sequel, mi...  
3  [dc comics, crime fighter, terrorist, secret i...  
4  [based on novel, mars, medallion, space travel...

In [ ]:
movies.iloc[0].crew

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"},

In [ ]:
#convert into list of ooonly directors name
def convert_crew(obj):
  lst=[]
  for i in ast.literal_eval(obj):
    if(i['job']=='Director'):
      lst.append(i['name'])
  return lst

In [ ]:
movies['crew']=movies['crew'].apply(convert_crew)

In [ ]:
movies.head()

movie_id                                              cast  \
0     19995  [Sam Worthington, Zoe Saldana, Sigourney Weaver]   
1       285     [Johnny Depp, Orlando Bloom, Keira Knightley]   
2    206647      [Daniel Craig, Christoph Waltz, Léa Seydoux]   
3     49026      [Christian Bale, Michael Caine, Gary Oldman]   
4     49529    [Taylor Kitsch, Lynn Collins, Samantha Morton]   

                  crew                                     title  runtime  \
0      [James Cameron]                                    Avatar    162.0   
1     [Gore Verbinski]  Pirates of the Caribbean: At World's End    169.0   
2         [Sam Mendes]                                   Spectre    148.0   
3  [Christopher Nolan]                     The Dark Knight Rises    165.0   
4     [Andrew Stanton]                               John Carter    132.0   

     year                                           overview  \
0  2009.0  In the 22nd century, a paraplegic Marine is di...   
1  2007.0  Captain Barbossa, long believed to be dead, ha...   
2  2015.0  A cryptic message from Bond’s past sends him o...   
3  2012.0  Following the death of District Attorney Harve...   
4  2012.0  John Carter is a war-weary, former military ca...   

                                          genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  
0  [culture clash, future, space war, space colon...  
1  [ocean, drug abuse, exotic island, east india ...  
2  [spy, based on novel, secret agent, sequel, mi...  
3  [dc comics, crime fighter, terrorist, secret i...  
4  [based on novel, mars, medallion, space travel...

In [ ]:
#make overview to a list so we can process it
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [ ]:
# now we will remove space from names between first and last name to remove ambiguit like if one name is sam and other last name is sam than it will get confuse to get which one
# also it will make fanstasy horror which a genre but it is look like two different genere so we will remove space btw them
movies['crew']=movies['crew'].apply(lambda x:[i.replace(" ","") for i in x])
movies['cast']=movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
movies['genres']=movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
movies['keywords']=movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])


In [ ]:
movies.head()

movie_id                                           cast  \
0     19995  [SamWorthington, ZoeSaldana, SigourneyWeaver]   
1       285     [JohnnyDepp, OrlandoBloom, KeiraKnightley]   
2    206647      [DanielCraig, ChristophWaltz, LéaSeydoux]   
3     49026      [ChristianBale, MichaelCaine, GaryOldman]   
4     49529    [TaylorKitsch, LynnCollins, SamanthaMorton]   

                 crew                                     title  runtime  \
0      [JamesCameron]                                    Avatar    162.0   
1     [GoreVerbinski]  Pirates of the Caribbean: At World's End    169.0   
2         [SamMendes]                                   Spectre    148.0   
3  [ChristopherNolan]                     The Dark Knight Rises    165.0   
4     [AndrewStanton]                               John Carter    132.0   

     year                                           overview  \
0  2009.0  [In, the, 22nd, century,, a, paraplegic, Marin...   
1  2007.0  [Captain, Barbossa,, long, believed, to, be, d...   
2  2015.0  [A, cryptic, message, from, Bond’s, past, send...   
3  2012.0  [Following, the, death, of, District, Attorney...   
4  2012.0  [John, Carter, is, a, war-weary,, former, mili...   

                                         genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   
2                    [Action, Adventure, Crime]   
3              [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, ScienceFiction]   

                                            keywords  
0  [cultureclash, future, spacewar, spacecolony, ...  
1  [ocean, drugabuse, exoticisland, eastindiatrad...  
2  [spy, basedonnovel, secretagent, sequel, mi6, ...  
3  [dccomics, crimefighter, terrorist, secretiden...  
4  [basedonnovel, mars, medallion, spacetravel, p...

In [ ]:
#make a new colmn tags so well we use that column to find similar movies maching all tags values
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']
movies['tags'][0]

['In',
 'the',
 '22nd',
 'century,',
 'a',
 'paraplegic',
 'Marine',
 'is',
 'dispatched',
 'to',
 'the',
 'moon',
 'Pandora',
 'on',
 'a',
 'unique',
 'mission,',
 'but',
 'becomes',
 'torn',
 'between',
 'following',
 'orders',
 'and',
 'protecting',
 'an',
 'alien',
 'civilization.',
 'Action',
 'Adventure',
 'Fantasy',
 'ScienceFiction',
 'cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d',
 'SamWorthington',
 'ZoeSaldana',
 'SigourneyWeaver',
 'JamesCameron']

In [ ]:
#new dataframe with less and important features
new_mov = movies[['movie_id','title','tags','runtime','year']]

In [ ]:
#make tags list to string
new_mov['tags'] = new_mov['tags'].apply(lambda x:" ".join(x))
print(new_mov.head())
new_mov['tags'] = new_mov['tags'].apply(lambda x: x.lower())
print(new_mov.iloc[0].tags)
new_mov.isnull().sum()

   movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  runtime    year  
0  i n   t h e   2 2 n d   c e n t u r y ,   a   ...    162.0  2009.0  
1  c a p t a i n   b a r b o s s a ,   l o n g   ...    169.0  2007.0  
2  a   c r y p t i c   m e s s a g   f r o m   b ...    148.0  2015.0  
3  f o l l o w   t h e   d e a t h   o f   d i s ...    165.0  2012.0  
4  j o h n   c a r t e r   i s   a   w a r - w e ...    132.0  2012.0  
i n   t h e   2 2 n d   c e n t u r y ,   a   p a r a p l e g   m a r i n   i s   d i s p a t c h   t o   t h e   m o o n   p a n d o r a   o n   a   u n i q u   m i s s i o n ,   b u t   b e c o m   t o r n   b e t w e e n  

<ipython-input-110-4de6065ddf2a>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov['tags'] = new_mov['tags'].apply(lambda x:" ".join(x))
<ipython-input-110-4de6065ddf2a>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov['tags'] = new_mov['tags'].apply(lambda x: x.lower())


movie_id    0
title       0
tags        0
runtime     0
year        0
dtype: int64

In [ ]:
print(new_mov['tags'][0])

i n   t h e   2 2 n d   c e n t u r y ,   a   p a r a p l e g   m a r i n   i s   d i s p a t c h   t o   t h e   m o o n   p a n d o r a   o n   a   u n i q u   m i s s i o n ,   b u t   b e c o m   t o r n   b e t w e e n   f o l l o w   o r d e r   a n d   p r o t e c t   a n   a l i e n   c i v i l i z a t i o n .   a c t i o n   a d v e n t u r   f a n t a s i   s c i e n c e f i c t   c u l t u r e c l a s h   f u t u r   s p a c e w a r   s p a c e c o l o n i   s o c i e t i   s p a c e t r a v e l   f u t u r i s t   r o m a n c   s p a c e   a l i e n   t r i b e   a l i e n p l a n e t   c g i   m a r i n   s o l d i e r   b a t t l   l o v e a f f a i r   a n t i w a r   p o w e r r e l   m i n d a n d s o u l   3 d   s a m w o r t h i n g t o n   z o e s a l d a n a   s i g o u r n e y w e a v   j a m e s c a m e r o n


In [ ]:
# in tags there is problem that words like action and actions have same meaning
#so we will use stemming to make it same so our syystem do not get confused and treat them as different entitity
#so there is a nltk libarry to do this
from nltk.stem.porter import PorterStemmer
pt = PorterStemmer()
def stemi(text):
  p=[]
  for i in  text.split():
    p.append(pt.stem(i))
  return " ".join(p)
#lets check with a exmple
stemi('In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCamero')
#now we will do this for all tag rows
new_mov['tags'] = new_mov['tags'].apply(stemi)
new_mov.head()
new_mov['tags'].shape

<ipython-input-96-01434f6d3512>:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_mov['tags'] = new_mov['tags'].apply(stemi)


(4806,)

In [ ]:
 #now we will remove stop words like is, a, are bcs tha is not gonna impact our decion making
#than we will create matrix to store all word pointing to an number and if we got a new movie than we check distance of that  movie
#matrix from other movie matrix  (i.e, distance between vectors of one movie and other based on features )
#less distnce show more similarity

# lets have egmaple with TfidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "Action thriller adventure",
    "Romantic comedy drama",
    "Science fiction space opera"
]

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(documents)
print(X)
feature_names = vectorizer.get_feature_names_out()
print("Feature Names:")
print(feature_names)

# lets have egmaple with  CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1000,stop_words='english')
X = vectorizer.fit_transform(documents).toarray()
print(X)

#TfidfVectorizer gives more foucus on unique values and less weight to coomon values
#  CountVectorizer  gives values to words
#TF-IDF(t,d,D)=TF(t,d)×IDF(t,D)
#TF(t,d)= Number of times term t appears in document d / total number of terms in document d

  (0, 0)	0.5773502691896257
  (0, 9)	0.5773502691896257
  (0, 1)	0.5773502691896257
  (1, 6)	0.5773502691896257
  (1, 2)	0.5773502691896257
  (1, 3)	0.5773502691896257
  (2, 7)	0.5
  (2, 4)	0.5
  (2, 8)	0.5
  (2, 5)	0.5
Feature Names:
['action' 'adventure' 'comedy' 'drama' 'fiction' 'opera' 'romantic'
 'science' 'space' 'thriller']
[[1 1 0 0 0 0 0 0 0 1]
 [0 0 1 1 0 0 1 0 0 0]
 [0 0 0 0 1 1 0 1 1 0]]


In [ ]:
#now we will do transformation from string to numercal array on our movie data
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_features=5000, stop_words='english')
vector = vectorizer.fit_transform(new_mov['tags']).toarray()
print(vector)
feature_names = vectorizer.get_feature_names_out()
print(feature_names)
print((vector.shape))

array2 = np.array(new_mov['year'])
print(array2.shape)
#reshape
array2 = array2.reshape(-1, 1)
# Append Series as a new row
vector = np.concatenate((vector, array2), axis=1)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
['000' '007' '10' ... 'zone' 'zoo' 'zooeydeschanel']
(4806, 5000)
(4806,)


WE will use cosine distance instead of eculidian distance  bcs In high-dimensional spaces, the distances between any two points tend to become very similar. This is because the relative difference between the distances of points becomes less significant as the number of dimensions increases. cosine and similarity inversely proportional

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [ ]:
print(similarity[0])
similarity.shape

[1.         0.99999976 0.99999976 ... 0.99999976 0.99999975 0.99999975]


(4806, 4806)

In [ ]:
sorted(new_mov['title'])
pd.Series(sorted(new_mov['title'])).to_csv('name_column.csv', index=False)

In [ ]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(2405, 0.9999998125070886),
 (3728, 0.999999808604719),
 (582, 0.9999998004768884),
 (1214, 0.9999997987345651),
 (3606, 0.9999997962532432)]

In [ ]:
# function gets movie name that of user will want similar movies
def movie_recom(movie):
  # first it will match movie name with data and give index or row no. of taht movie
  movie_index = new_mov[new_mov['title'] == movie].index[0]
  #than we will get distances to all other movies from taht movie
  #and least distance willl be most similar so we have to sort
  #but if we sort than index will get diturbed any index can be at any postion
  # than we canniot see this index distrance is related to which movie  so
  #we have to make something that will have relation to every movie index that will not change
  #so enumrate function will do that
  distances = similarity[movie_index]
  movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:20]
  #lamda help to sort value based on distances and not on enumurate given index
  #[1:20] will make sure it will only give 20-1 = 19 movie reccomendtion
  # i[0] will give movie row no. realted to distance and iloc will takes us to that column tahn we will use itle to get movie titles
  for i in movie_list:
    print(new_mov.iloc[i[0]].title)



In [ ]:
movie_recom('Kick-Ass')

Kick-Ass 2
Chasing Amy
The Incredibles
Defendor
The Spirit
The Last Godfather
Spider-Man
American Splendor
Superhero Movie
Griff the Invisible
Batman v Superman: Dawn of Justice
The Prince & Me
Nowhere Boy
The Specials
Rockaway
Napoleon Dynamite
Taxman
Let Me In
Batman Begins


In [ ]:
import pickle
new_mov.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                tags  runtime    year  
0  in the 22nd century, a parapleg marin is dispa...    162.0  2009.0  
1  captain barbossa, long believ to be dead, ha c...    169.0  2007.0  
2  a cryptic messag from bond’ past send him on a...    148.0  2015.0  
3  follow the death of district attorney harvey d...    165.0  2012.0  
4  john carter is a war-weary, former militari ca...    132.0  2012.0

In [ ]:
pickle.dump(new_mov.to_dict(),open('movies_dict.pkl','wb'))

In [ ]:
pickle.dump(similarity,open('similarity.pkl','wb'))